const properties = {
  h: {
    atomicNumber: 1,
    symbol: "H",
    fullName: "Hydrogen",
    electronicConfiguration: "1s1",
    position: "G1 P1",
    atomicWeight: 1.008,
    atomicRadius: 53,
    density: 0.00008988,
    state: "Gas",
    meltingPoint: 14.01,
    boilingPoint: 20.28,
    oxidationState: [1, -1],
    electronegativity: 2.2,
    electronGainEnthalpy: -72.8,
    electronAffinity: 72.8,
    protonAffinity: 1676,
    autoIgnitionTemperature: 500,
    airSensitivity: "Non-reactive",
    url: "element/hydrogen.html",
  },
  he: {
    atomicNumber: 2,
    symbol: "He",
    fullName: "Helium",
    electronicConfiguration: "1s2",
    position: "G18 P1",
    atomicWeight: 4.002602,
    atomicRadius: 31,
    density: 0.0001785,
    state: "Gas",
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    oxidationState: [0],
    electronegativity: null,
    electronGainEnthalpy: null,
    electronAffinity: null,
    protonAffinity: 177.8,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Non-reactive",
    url: "element/helium.html",
  },
  li: {
    atomicNumber: 3,
    symbol: "Li",
    fullName: "Lithium",
    electronicConfiguration: "[He] 2s1",
    position: "G1 P2",
    atomicWeight: 6.94,
    atomicRadius: 167,
    density: 0.534,
    state: "Solid",
    meltingPoint: 453.69,
    boilingPoint: 1603,
    oxidationState: [1],
    electronegativity: 0.98,
    electronGainEnthalpy: -60,
    electronAffinity: 59.6,
    protonAffinity: 920.9,
    autoIgnitionTemperature: 200,
    airSensitivity: "Reacts with air",
    url: "element/lithium.html",
  },
  be: {
    atomicNumber: 4,
    symbol: "Be",
    fullName: "Beryllium",
    electronicConfiguration: "[He] 2s2",
    position: "G2 P2",
    atomicWeight: 9.0122,
    atomicRadius: 112,
    density: 1.848,
    state: "Solid",
    meltingPoint: 1560,
    boilingPoint: 2742,
    oxidationState: [2],
    electronegativity: 1.57,
    electronGainEnthalpy: -48,
    electronAffinity: null,
    protonAffinity: 757.1,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Forms oxide layer",
    url: "element/beryllium.html",
  },
  b: {
    atomicNumber: 5,
    symbol: "B",
    fullName: "Boron",
    electronicConfiguration: "[He] 2s2 2p1",
    position: "G13 P2",
    atomicWeight: 10.81,
    atomicRadius: 87,
    density: 2.34,
    state: "Solid",
    meltingPoint: 2349,
    boilingPoint: 4200,
    oxidationState: [3],
    electronegativity: 2.04,
    electronGainEnthalpy: -27,
    electronAffinity: 26.7,
    protonAffinity: 587.1,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Forms oxide layer",
    url: "element/boron.html",
  },
  c: {
    atomicNumber: 6,
    symbol: "C",
    fullName: "Carbon",
    electronicConfiguration: "[He] 2s2 2p2",
    position: "G14 P2",
    atomicWeight: 12.011,
    atomicRadius: 67,
    density: 2.267,
    state: "Solid",
    meltingPoint: 3823,
    boilingPoint: 4300,
    oxidationState: [4, 2, -4],
    electronegativity: 2.55,
    electronGainEnthalpy: -122.3,
    electronAffinity: 153.9,
    protonAffinity: 493.6,
    autoIgnitionTemperature: 700,
    airSensitivity: "Forms CO and CO2",
    url: "element/carbon.html",
  },
  n: {
    atomicNumber: 7,
    symbol: "N",
    fullName: "Nitrogen",
    electronicConfiguration: "[He] 2s2 2p3",
    position: "G15 P2",
    atomicWeight: 14.007,
    atomicRadius: 56,
    density: 0.0012506,
    state: "Gas",
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    oxidationState: [5, 4, 3, 2, 1, -1, -2, -3],
    electronegativity: 3.04,
    electronGainEnthalpy: -6.8,
    electronAffinity: 7,
    protonAffinity: 428.6,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Non-reactive",
    url: "element/nitrogen.html",
  },
  o: {
    atomicNumber: 8,
    symbol: "O",
    fullName: "Oxygen",
    electronicConfiguration: "[He] 2s2 2p4",
    position: "G16 P2",
    atomicWeight: 15.999,
    atomicRadius: 48,
    density: 0.001429,
    state: "Gas",
    meltingPoint: 54.36,
    boilingPoint: 90.2,
    oxidationState: [2, -2],
    electronegativity: 3.44,
    electronGainEnthalpy: -141,
    electronAffinity: 140.976,
    protonAffinity: 420.8,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Forms oxides",
    url: "element/oxygen.html",
  },
  f: {
    atomicNumber: 9,
    symbol: "F",
    fullName: "Fluorine",
    electronicConfiguration: "[He] 2s2 2p5",
    position: "G17 P2",
    atomicWeight: 18.998,
    atomicRadius: 42,
    density: 0.001696,
    state: "Gas",
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    oxidationState: [-1],
    electronegativity: 3.98,
    electronGainEnthalpy: -328,
    electronAffinity: 328.1649,
    protonAffinity: 343.4,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Forms fluorides",
    url: "element/fluorine.html",
  },
  ne: {
    atomicNumber: 10,
    symbol: "Ne",
    fullName: "Neon",
    electronicConfiguration: "[He] 2s2 2p6",
    position: "G18 P2",
    atomicWeight: 20.18,
    atomicRadius: 38,
    density: 0.0008999,
    state: "Gas",
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    oxidationState: [0],
    electronegativity: null,
    electronGainEnthalpy: null,
    electronAffinity: null,
    protonAffinity: 170.1,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Non-reactive",
    url: "element/neon.html",
  },
  na: {
    atomicNumber: 11,
    symbol: "Na",
    fullName: "Sodium",
    electronicConfiguration: "[Ne] 3s1",
    position: "G1 P3",
    atomicWeight: 22.99,
    atomicRadius: 186,
    density: 0.968,
    state: "Solid",
    meltingPoint: 97.72,
    boilingPoint: 883,
    oxidationState: [1],
    electronegativity: 0.93,
    electronGainEnthalpy: 52.8,
    electronAffinity: 52.8,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Highly reactive",
    url: "element/sodium.html",
  },
  mg: {
    atomicNumber: 12,
    symbol: "Mg",
    fullName: "Magnesium",
    electronicConfiguration: "[Ne] 3s2",
    position: "G2 P3",
    atomicWeight: 24.305,
    atomicRadius: 160,
    density: 1.738,
    state: "Solid",
    meltingPoint: 650,
    boilingPoint: 1090,
    oxidationState: [2],
    electronegativity: 1.31,
    electronGainEnthalpy: -0.4,
    electronAffinity: -0.4,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/magnesium.html",
  },
  al: {
    atomicNumber: 13,
    symbol: "Al",
    fullName: "Aluminum",
    electronicConfiguration: "[Ne] 3s2 3p1",
    position: "G13 P3",
    atomicWeight: 26.982,
    atomicRadius: 143,
    density: 2.7,
    state: "Solid",
    meltingPoint: 660,
    boilingPoint: 2519,
    oxidationState: [3],
    electronegativity: 1.61,
    electronGainEnthalpy: -0.43,
    electronAffinity: -0.43,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/aluminium.html",
  },
  si: {
    atomicNumber: 14,
    symbol: "Si",
    fullName: "Silicon",
    electronicConfiguration: "[Ne] 3s2 3p2",
    position: "G14 P3",
    atomicWeight: 28.085,
    atomicRadius: 118,
    density: 2.33,
    state: "Solid",
    meltingPoint: 1414,
    boilingPoint: 2900,
    oxidationState: [4, -4],
    electronegativity: 1.9,
    electronGainEnthalpy: -0.23,
    electronAffinity: -0.23,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/silicon.html",
  },
  p: {
    atomicNumber: 15,
    symbol: "P",
    fullName: "Phosphorus",
    electronicConfiguration: "[Ne] 3s2 3p3",
    position: "G15 P3",
    atomicWeight: 30.974,
    atomicRadius: 110,
    density: 1.82,
    state: "Solid",
    meltingPoint: 44,
    boilingPoint: 280,
    oxidationState: [3, 5],
    electronegativity: 2.19,
    electronGainEnthalpy: -0.75,
    electronAffinity: -0.75,
    protonAffinity: 0,
    autoIgnitionTemperature: "White phosphorus: 34°C",
    airSensitivity: "Highly reactive",
    url: "element/phosphorus.html",
  },
  s: {
    atomicNumber: 16,
    symbol: "S",
    fullName: "Sulfur",
    electronicConfiguration: "[Ne] 3s2 3p4",
    position: "G16 P3",
    atomicWeight: 32.07,
    atomicRadius: 104,
    density: 2.07,
    state: "Solid",
    meltingPoint: 115,
    boilingPoint: 444,
    oxidationState: [2, 4, 6],
    electronegativity: 2.58,
    electronGainEnthalpy: -2.07,
    electronAffinity: -2.07,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/sulfur.html",
  },
  cl: {
    atomicNumber: 17,
    symbol: "Cl",
    fullName: "Chlorine",
    electronicConfiguration: "[Ne] 3s2 3p5",
    position: "G17 P3",
    atomicWeight: 35.45,
    atomicRadius: 99,
    density: 0.0032,
    state: "Gas",
    meltingPoint: -101,
    boilingPoint: -34,
    oxidationState: [-1, 1, 3, 5, 7],
    electronegativity: 3.16,
    electronGainEnthalpy: -349,
    electronAffinity: -349,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/chlorine.html",
  },
  ar: {
    atomicNumber: 18,
    symbol: "Ar",
    fullName: "Argon",
    electronicConfiguration: "[Ne] 3s2 3p6",
    position: "G18 P3",
    atomicWeight: 39.948,
    atomicRadius: 71,
    density: 0.00178,
    state: "Gas",
    meltingPoint: -189.4,
    boilingPoint: -185.8,
    oxidationState: "Inert",
    electronegativity: "N/A",
    electronGainEnthalpy: "N/A",
    electronAffinity: "N/A",
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/argon.html",
  },
  k: {
    atomicNumber: 19,
    symbol: "K",
    fullName: "Potassium",
    electronicConfiguration: "[Ar] 4s1",
    position: "G1 P4",
    atomicWeight: 39.098,
    atomicRadius: 203,
    density: 0.856,
    state: "Solid",
    meltingPoint: 63.5,
    boilingPoint: 759,
    oxidationState: [1],
    electronegativity: 0.82,
    electronGainEnthalpy: 0.48,
    electronAffinity: 0.48,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Highly reactive",
    url: "element/potassium.html",
  },
  ca: {
    atomicNumber: 20,
    symbol: "Ca",
    fullName: "Calcium",
    electronicConfiguration: "[Ar] 4s2",
    position: "G2 P4",
    atomicWeight: 40.078,
    atomicRadius: 197,
    density: 1.54,
    state: "Solid",
    meltingPoint: 842,
    boilingPoint: 1484,
    oxidationState: [2],
    electronegativity: 1.0,
    electronGainEnthalpy: 0.02,
    electronAffinity: 0.02,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/calcium.html",
  },
  sc: {
    atomicNumber: 21,
    symbol: "Sc",
    fullName: "Scandium",
    electronicConfiguration: "[Ar] 3d1 4s2",
    position: "G3 P4",
    atomicWeight: 44.956,
    atomicRadius: 162,
    density: 2.98,
    state: "Solid",
    meltingPoint: 1541,
    boilingPoint: 2836,
    oxidationState: [3],
    electronegativity: 1.36,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/scandium.html",
  },
  ti: {
    atomicNumber: 22,
    symbol: "Ti",
    fullName: "Titanium",
    electronicConfiguration: "[Ar] 3d2 4s2",
    position: "G4 P4",
    atomicWeight: 47.867,
    atomicRadius: 176,
    density: 4.54,
    state: "Solid",
    meltingPoint: 1885,
    boilingPoint: 3225,
    oxidationState: [2, 3, 4],
    electronegativity: 1.54,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/titanium.html",
  },
  v: {
    atomicNumber: 23,
    symbol: "V",
    fullName: "Vanadium",
    electronicConfiguration: "[Ar] 3d3 4s2",
    position: "G5 P4",
    atomicWeight: 50.942,
    atomicRadius: 141,
    density: 6.11,
    state: "Solid",
    meltingPoint: 1910,
    boilingPoint: 3407,
    oxidationState: [2, 3, 4, 5],
    electronegativity: 1.63,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/vanadium.html",
  },
  cr: {
    atomicNumber: 24,
    symbol: "Cr",
    fullName: "Chromium",
    electronicConfiguration: "[Ar] 3d5 4s1",
    position: "G6 P4",
    atomicWeight: 51.996,
    atomicRadius: 140,
    density: 7.19,
    state: "Solid",
    meltingPoint: 1907,
    boilingPoint: 2671,
    oxidationState: [2, 3, 6],
    electronegativity: 1.66,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/chromium.html",
  },
  mn: {
    atomicNumber: 25,
    symbol: "Mn",
    fullName: "Manganese",
    electronicConfiguration: "[Ar] 3d5 4s2",
    position: "G7 P4",
    atomicWeight: 54.938,
    atomicRadius: 139,
    density: 7.43,
    state: "Solid",
    meltingPoint: 1246,
    boilingPoint: 2095,
    oxidationState: [2, 3, 4, 6, 7],
    electronegativity: 1.55,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/manganese.html",
  },
  fe: {
    atomicNumber: 26,
    symbol: "Fe",
    fullName: "Iron",
    electronicConfiguration: "[Ar] 3d6 4s2",
    position: "G8 P4",
    atomicWeight: 55.845,
    atomicRadius: 140,
    density: 7.87,
    state: "Solid",
    meltingPoint: 1538,
    boilingPoint: 2862,
    oxidationState: [2, 3],
    electronegativity: 1.83,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable, but can rust",
    url: "element/iron.html",
  },
  co: {
    atomicNumber: 27,
    symbol: "Co",
    fullName: "Cobalt",
    electronicConfiguration: "[Ar] 3d7 4s2",
    position: "G9 P4",
    atomicWeight: 58.933,
    atomicRadius: 125,
    density: 8.9,
    state: "Solid",
    meltingPoint: 1495,
    boilingPoint: 2927,
    oxidationState: [2, 3],
    electronegativity: 1.88,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable, but can oxidize",
    url: "element/cobalt.html",
  },
  ni: {
    atomicNumber: 28,
    symbol: "Ni",
    fullName: "Nickel",
    electronicConfiguration: "[Ar] 3d8 4s2",
    position: "G10 P4",
    atomicWeight: 58.933,
    atomicRadius: 124,
    density: 8.91,
    state: "Solid",
    meltingPoint: 1455,
    boilingPoint: 2913,
    oxidationState: [2, 3],
    electronegativity: 1.91,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable, but can oxidize",
    url: "element/nickel.html",
  },
  cu: {
    atomicNumber: 29,
    symbol: "Cu",
    fullName: "Copper",
    electronicConfiguration: "[Ar] 3d10 4s1",
    position: "G11 P4",
    atomicWeight: 63.546,
    atomicRadius: 135,
    density: 8.96,
    state: "Solid",
    meltingPoint: 1084,
    boilingPoint: 2562,
    oxidationState: [1, 2],
    electronegativity: 1.9,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable, but can tarnish",
    url: "element/copper.html",
  },
  zn: {
    atomicNumber: 30,
    symbol: "Zn",
    fullName: "Zinc",
    electronicConfiguration: "[Ar] 3d10 4s2",
    position: "G12 P4",
    atomicWeight: 65.38,
    atomicRadius: 139,
    density: 7.14,
    state: "Solid",
    meltingPoint: 419.5,
    boilingPoint: 907,
    oxidationState: [2],
    electronegativity: 1.65,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable, but can form a coating of zinc oxide",
    url: "element/zinc.html",
  },
  ga: {
    atomicNumber: 31,
    symbol: "Ga",
    fullName: "Gallium",
    electronicConfiguration: "[Ar] 3d10 4s2 4p1",
    position: "G13 P4",
    atomicWeight: 69.723,
    atomicRadius: 136,
    density: 5.91,
    state: "Solid",
    meltingPoint: 29.76,
    boilingPoint: 2204,
    oxidationState: [3],
    electronegativity: 1.81,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/gallium.html",
  },
  ge: {
    atomicNumber: 32,
    symbol: "Ge",
    fullName: "Germanium",
    electronicConfiguration: "[Ar] 3d10 4s2 4p2",
    position: "G14 P4",
    atomicWeight: 72.63,
    atomicRadius: 122,
    density: 5.323,
    state: "Solid",
    meltingPoint: 938.3,
    boilingPoint: 2833,
    oxidationState: [2, 4],
    electronegativity: 2.01,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/germanium.html",
  },
  as: {
    atomicNumber: 33,
    symbol: "As",
    fullName: "Arsenic",
    electronicConfiguration: "[Ar] 3d10 4s2 4p3",
    position: "G15 P4",
    atomicWeight: 74.921,
    atomicRadius: 119,
    density: 5.72,
    state: "Solid",
    meltingPoint: 817,
    boilingPoint: 614,
    oxidationState: [3, 5],
    electronegativity: 2.18,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/arsenic.html",
  },
  se: {
    atomicNumber: 34,
    symbol: "Se",
    fullName: "Selenium",
    electronicConfiguration: "[Ar] 3d10 4s2 4p4",
    position: "G16 P4",
    atomicWeight: 78.971,
    atomicRadius: 118,
    density: 4.82,
    state: "Solid",
    meltingPoint: 221,
    boilingPoint: 685,
    oxidationState: [-2, +2, +4, +6],
    electronegativity: 2.55,
    electronGainEnthalpy: -0.75,
    electronAffinity: -0.75,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/selenium.html",
  },
  br: {
    atomicNumber: 35,
    symbol: "Br",
    fullName: "Bromine",
    electronicConfiguration: "[Ar] 3d10 4s2 4p5",
    position: "G17 P4",
    atomicWeight: 79.904,
    atomicRadius: 114,
    density: 3.102,
    state: "Liquid",
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    oxidationState: [-1, +1, +3, +5, +7],
    electronegativity: 2.96,
    electronGainEnthalpy: -324,
    electronAffinity: -324,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/bromine.html",
  },
  kr: {
    atomicNumber: 36,
    symbol: "Kr",
    fullName: "Krypton",
    electronicConfiguration: "[Ar] 3d10 4s2 4p6",
    position: "G18 P4",
    atomicWeight: 83.798,
    atomicRadius: 88,
    density: 0.00373,
    state: "Gas",
    meltingPoint: -157.4,
    boilingPoint: -153.2,
    oxidationState: "Inert",
    electronegativity: "N/A",
    electronGainEnthalpy: "N/A",
    electronAffinity: "N/A",
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/krypton.html",
  },
  rb: {
    atomicNumber: 37,
    symbol: "Rb",
    fullName: "Rubidium",
    electronicConfiguration: "[Kr] 5s1",
    position: "G1 P5",
    atomicWeight: 85.468,
    atomicRadius: 220,
    density: 1.53,
    state: "Solid",
    meltingPoint: 39.3,
    boilingPoint: 688,
    oxidationState: [1],
    electronegativity: 0.82,
    electronGainEnthalpy: 0.3,
    electronAffinity: 0.3,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Highly reactive",
    url: "element/rubidium.html",
  },
  sr: {
    atomicNumber: 38,
    symbol: "Sr",
    fullName: "Strontium",
    electronicConfiguration: "[Kr] 5s2",
    position: "G2 P5",
    atomicWeight: 87.62,
    atomicRadius: 215,
    density: 2.64,
    state: "Solid",
    meltingPoint: 777,
    boilingPoint: 1382,
    oxidationState: [2],
    electronegativity: 0.95,
    electronGainEnthalpy: 0.06,
    electronAffinity: 0.06,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/strontium.html",
  },
  y: {
    atomicNumber: 39,
    symbol: "Y",
    fullName: "Yttrium",
    electronicConfiguration: "[Kr] 4d1 5s2",
    position: "G3 P5",
    atomicWeight: 88.905,
    atomicRadius: 180,
    density: 4.47,
    state: "Solid",
    meltingPoint: 1526,
    boilingPoint: 3339,
    oxidationState: [3],
    electronegativity: 1.22,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/yttrium.html",
  },
  zr: {
    atomicNumber: 40,
    symbol: "Zr",
    fullName: "Zirconium",
    electronicConfiguration: "[Kr] 4d2 5s2",
    position: "G4 P5",
    atomicWeight: 91.224,
    atomicRadius: 160,
    density: 6.52,
    state: "Solid",
    meltingPoint: 1855,
    boilingPoint: 4409,
    oxidationState: [4],
    electronegativity: 1.33,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/zirconium.html",
  },
  nb: {
    atomicNumber: 41,
    symbol: "Nb",
    fullName: "Niobium",
    electronicConfiguration: "[Kr] 4d4 5s1",
    position: "G5 P5",
    atomicWeight: 92.906,
    atomicRadius: 146,
    density: 8.57,
    state: "Solid",
    meltingPoint: 2477,
    boilingPoint: 4744,
    oxidationState: [3, 5],
    electronegativity: 1.6,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/niobium.html",
  },
  mo: {
    atomicNumber: 42,
    symbol: "Mo",
    fullName: "Molybdenum",
    electronicConfiguration: "[Kr] 4d5 5s1",
    position: "G6 P5",
    atomicWeight: 95.95,
    atomicRadius: 139,
    density: 10.28,
    state: "Solid",
    meltingPoint: 2623,
    boilingPoint: 4639,
    oxidationState: [2, 3, 4, 5, 6],
    electronegativity: 2.16,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/molybdenum.html",
  },
  tc: {
    atomicNumber: 43,
    symbol: "Tc",
    fullName: "Technetium",
    electronicConfiguration: "[Kr] 4d5 5s2",
    position: "G7 P5",
    atomicWeight: 98,
    atomicRadius: 126,
    density: 11.5,
    state: "Solid",
    meltingPoint: 2157,
    boilingPoint: 4265,
    oxidationState: [7, 6, 5, 4, 3, 2, 1],
    electronegativity: 1.9,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/technetium.html",
  },
  ru: {
    atomicNumber: 44,
    symbol: "Ru",
    fullName: "Ruthenium",
    electronicConfiguration: "[Kr] 4d7 5s1",
    position: "G8 P5",
    atomicWeight: 101.07,
    atomicRadius: 138,
    density: 12.37,
    state: "Solid",
    meltingPoint: 2334,
    boilingPoint: 4150,
    oxidationState: [2, 3, 4, 6],
    electronegativity: 2.2,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/ruthenium.html",
  },
  rh: {
    atomicNumber: 45,
    symbol: "Rh",
    fullName: "Rhodium",
    electronicConfiguration: "[Kr] 4d8 5s1",
    position: "G9 P5",
    atomicWeight: 102.91,
    atomicRadius: 139,
    density: 12.41,
    state: "Solid",
    meltingPoint: 1964,
    boilingPoint: 3695,
    oxidationState: [1, 2, 3, 4, 5],
    electronegativity: 2.28,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/rhodium.html",
  },
  pd: {
    atomicNumber: 46,
    symbol: "Pd",
    fullName: "Palladium",
    electronicConfiguration: "[Kr] 4d10",
    position: "G10 P5",
    atomicWeight: 106.42,
    atomicRadius: 144,
    density: 12.02,
    state: "Solid",
    meltingPoint: 1554,
    boilingPoint: 2963,
    oxidationState: [0, 1, 2, 4],
    electronegativity: 2.2,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/palladium.html",
  },
  ag: {
    atomicNumber: 47,
    symbol: "Ag",
    fullName: "Silver",
    electronicConfiguration: "[Kr] 4d10 5s1",
    position: "G11 P5",
    atomicWeight: 107.87,
    atomicRadius: 144,
    density: 10.49,
    state: "Solid",
    meltingPoint: 961.8,
    boilingPoint: 2162,
    oxidationState: [1, 2],
    electronegativity: 1.93,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/silver.html",
  },
  cd: {
    atomicNumber: 48,
    symbol: "Cd",
    fullName: "Cadmium",
    electronicConfiguration: "[Kr] 4d10 5s2",
    position: "G12 P5",
    atomicWeight: 112.41,
    atomicRadius: 148,
    density: 8.65,
    state: "Solid",
    meltingPoint: 321.1,
    boilingPoint: 767,
    oxidationState: [2],
    electronegativity: 1.69,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/cadmium.html",
  },
  ind: {
    atomicNumber: 49,
    symbol: "In",
    fullName: "Indium",
    electronicConfiguration: "[Kr] 4d10 5s2 5p1",
    position: "G13 P5",
    atomicWeight: 114.82,
    atomicRadius: 150,
    density: 7.31,
    state: "Solid",
    meltingPoint: 156.6,
    boilingPoint: 2072,
    oxidationState: [1, 3],
    electronegativity: 1.78,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/indium.html",
  },
  sn: {
    atomicNumber: 50,
    symbol: "Sn",
    fullName: "Tin",
    electronicConfiguration: "[Kr] 4d10 5s2 5p2",
    position: "G14 P5",
    atomicWeight: 118.71,
    atomicRadius: 145,
    density: 7.31,
    state: "Solid",
    meltingPoint: 231.9,
    boilingPoint: 2602,
    oxidationState: [2, 4],
    electronegativity: 1.96,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/tin.html",
  },
  sb: {
    atomicNumber: 51,
    symbol: "Sb",
    fullName: "Antimony",
    electronicConfiguration: "[Kr] 4d10 5s2 5p3",
    position: "G15 P5",
    atomicWeight: 121.76,
    atomicRadius: 141,
    density: 6.697,
    state: "Solid",
    meltingPoint: 630.6,
    boilingPoint: 1587,
    oxidationState: [-3, 3, 5],
    electronegativity: 2.05,
    electronGainEnthalpy: -0.32,
    electronAffinity: -0.32,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/antimony.html",
  },
  te: {
    atomicNumber: 52,
    symbol: "Te",
    fullName: "Tellurium",
    electronicConfiguration: "[Kr] 4d10 5s2 5p4",
    position: "G16 P5",
    atomicWeight: 127.6,
    atomicRadius: 135,
    density: 6.24,
    state: "Solid",
    meltingPoint: 449.5,
    boilingPoint: 988,
    oxidationState: [-2, 4, 6],
    electronegativity: 2.1,
    electronGainEnthalpy: -1.97,
    electronAffinity: -1.97,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/tellurium.html",
  },
  i: {
    atomicNumber: 53,
    symbol: "I",
    fullName: "Iodine",
    electronicConfiguration: "[Kr] 4d10 5s2 5p5",
    position: "G17 P5",
    atomicWeight: 126.9,
    atomicRadius: 133,
    density: 4.94,
    state: "Solid",
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    oxidationState: [-1, 1, 3, 5, 7],
    electronegativity: 2.66,
    electronGainEnthalpy: -3.06,
    electronAffinity: -3.06,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/iodine.html",
  },
  xe: {
    atomicNumber: 54,
    symbol: "Xe",
    fullName: "Xenon",
    electronicConfiguration: "[Kr] 4d10 5s2 5p6",
    position: "G18 P5",
    atomicWeight: 131.29,
    atomicRadius: 108,
    density: 0.0059,
    state: "Gas",
    meltingPoint: -111.8,
    boilingPoint: -108.0,
    oxidationState: [2, 4, 6, 8],
    electronegativity: 2.6,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/xenon.html",
  },
  cs: {
    atomicNumber: 55,
    symbol: "Cs",
    fullName: "Cesium",
    electronicConfiguration: "[Xe] 6s1",
    position: "G1 P6",
    atomicWeight: 132.91,
    atomicRadius: 225,
    density: 1.93,
    state: "Solid",
    meltingPoint: 28.5,
    boilingPoint: 671,
    oxidationState: [1],
    electronegativity: 0.79,
    electronGainEnthalpy: 0.47,
    electronAffinity: 0.47,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Highly reactive",
    url: "element/cesium.html",
  },
  ba: {
    atomicNumber: 56,
    symbol: "Ba",
    fullName: "Barium",
    electronicConfiguration: "[Xe] 6s2",
    position: "G2 P6",
    atomicWeight: 137.33,
    atomicRadius: 198,
    density: 3.62,
    state: "Solid",
    meltingPoint: 727,
    boilingPoint: 1845,
    oxidationState: [2],
    electronegativity: 0.89,
    electronGainEnthalpy: 0.15,
    electronAffinity: 0.15,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Highly reactive",
    url: "element/barium.html",
  },
  la: {
    atomicNumber: 57,
    symbol: "La",
    fullName: "Lanthanum",
    electronicConfiguration: "[Xe] 5d1 6s2",
    position: "G3 P6",
    atomicWeight: 138.91,
    atomicRadius: 169,
    density: 6.15,
    state: "Solid",
    meltingPoint: 920,
    boilingPoint: 3464,
    oxidationState: [3],
    electronegativity: 1.1,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/lanthanum.html",
  },
  ce: {
    atomicNumber: 58,
    symbol: "Ce",
    fullName: "Cerium",
    electronicConfiguration: "[Xe] 4f1 5d1 6s2",
    position: "G3 P6",
    atomicWeight: 140.12,
    atomicRadius: 165,
    density: 6.77,
    state: "Solid",
    meltingPoint: 798,
    boilingPoint: 3424,
    oxidationState: [3, 4],
    electronegativity: 1.12,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/cerium.html",
  },
  pr: {
    atomicNumber: 59,
    symbol: "Pr",
    fullName: "Praseodymium",
    electronicConfiguration: "[Xe] 4f3 6s2",
    position: "G3 P6",
    atomicWeight: 140.91,
    atomicRadius: 165,
    density: 6.77,
    state: "Solid",
    meltingPoint: 931,
    boilingPoint: 3520,
    oxidationState: [3, 4],
    electronegativity: 1.13,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/praseodymium.html",
  },
  nd: {
    atomicNumber: 60,
    symbol: "Nd",
    fullName: "Neodymium",
    electronicConfiguration: "[Xe] 4f4 6s2",
    position: "G3 P6",
    atomicWeight: 144.24,
    atomicRadius: 164,
    density: 7.01,
    state: "Solid",
    meltingPoint: 1024,
    boilingPoint: 3074,
    oxidationState: [3],
    electronegativity: 1.14,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/neodymium.html",
  },
  pm: {
    atomicNumber: 61,
    symbol: "Pm",
    fullName: "Promethium",
    electronicConfiguration: "[Xe] 4f5 6s2",
    position: "G3 P6",
    atomicWeight: 145,
    atomicRadius: 163,
    density: 7.26,
    state: "Solid",
    meltingPoint: 1100,
    boilingPoint: 3000,
    oxidationState: [3],
    electronegativity: 1.13,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/promethium.html",
  },
  sm: {
    atomicNumber: 62,
    symbol: "Sm",
    fullName: "Samarium",
    electronicConfiguration: "[Xe] 4f6 6s2",
    position: "G3 P6",
    atomicWeight: 150.36,
    atomicRadius: 180,
    density: 7.52,
    state: "Solid",
    meltingPoint: 1072,
    boilingPoint: 1900,
    oxidationState: [2, 3],
    electronegativity: 1.17,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/samarium.html",
  },
  eu: {
    atomicNumber: 63,
    symbol: "Eu",
    fullName: "Europium",
    electronicConfiguration: "[Xe] 4f7 6s2",
    position: "G3 P6",
    atomicWeight: 151.96,
    atomicRadius: 199,
    density: 5.24,
    state: "Solid",
    meltingPoint: 822,
    boilingPoint: 1529,
    oxidationState: [2, 3],
    electronegativity: 1.2,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/europium.html",
  },
  gd: {
    atomicNumber: 64,
    symbol: "Gd",
    fullName: "Gadolinium",
    electronicConfiguration: "[Xe] 4f7 5d1 6s2",
    position: "G3 P6",
    atomicWeight: 157.25,
    atomicRadius: 180,
    density: 7.9,
    state: "Solid",
    meltingPoint: 1313,
    boilingPoint: 3273,
    oxidationState: [3],
    electronegativity: 1.2,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/gadolinium.html",
  },
  tb: {
    atomicNumber: 65,
    symbol: "Tb",
    fullName: "Terbium",
    electronicConfiguration: "[Xe] 4f9 6s2",
    position: "G3 P6",
    atomicWeight: 158.93,
    atomicRadius: 177,
    density: 8.23,
    state: "Solid",
    meltingPoint: 1356,
    boilingPoint: 3230,
    oxidationState: [3, 4],
    electronegativity: 1.2,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/terbium.html",
  },
  dy: {
    atomicNumber: 66,
    symbol: "Dy",
    fullName: "Dysprosium",
    electronicConfiguration: "[Xe] 4f10 6s2",
    position: "G3 P6",
    atomicWeight: 162.5,
    atomicRadius: 178,
    density: 8.54,
    state: "Solid",
    meltingPoint: 1407,
    boilingPoint: 2562,
    oxidationState: [3],
    electronegativity: 1.22,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/dysprosium.html",
  },
  ho: {
    atomicNumber: 67,
    symbol: "Ho",
    fullName: "Holmium",
    electronicConfiguration: "[Xe] 4f11 6s2",
    position: "G3 P6",
    atomicWeight: 164.93,
    atomicRadius: 176,
    density: 8.8,
    state: "Solid",
    meltingPoint: 1461,
    boilingPoint: 2600,
    oxidationState: [3],
    electronegativity: 1.23,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/holmium.html",
  },
  er: {
    atomicNumber: 68,
    symbol: "Er",
    fullName: "Erbium",
    electronicConfiguration: "[Xe] 4f12 6s2",
    position: "G3 P6",
    atomicWeight: 167.26,
    atomicRadius: 176,
    density: 9.07,
    state: "Solid",
    meltingPoint: 1529,
    boilingPoint: 2868,
    oxidationState: [3],
    electronegativity: 1.24,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/erbium.html",
  },
  tm: {
    atomicNumber: 69,
    symbol: "Tm",
    fullName: "Thulium",
    electronicConfiguration: "[Xe] 4f13 6s2",
    position: "G3 P6",
    atomicWeight: 168.93,
    atomicRadius: 175,
    density: 9.32,
    state: "Solid",
    meltingPoint: 1545,
    boilingPoint: 1950,
    oxidationState: [3],
    electronegativity: 1.25,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/thulium.html",
  },
  yb: {
    atomicNumber: 70,
    symbol: "Yb",
    fullName: "Ytterbium",
    electronicConfiguration: "[Xe] 4f14 6s2",
    position: "G3 P6",
    atomicWeight: 173.04,
    atomicRadius: 175,
    density: 6.9,
    state: "Solid",
    meltingPoint: 824,
    boilingPoint: 1196,
    oxidationState: [2, 3],
    electronegativity: 1.1,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/ytterbium.html",
  },
  lu: {
    atomicNumber: 71,
    symbol: "Lu",
    fullName: "Lutetium",
    electronicConfiguration: "[Xe] 4f14 5d1 6s2",
    position: "G3 P6",
    atomicWeight: 174.97,
    atomicRadius: 172,
    density: 9.84,
    state: "Solid",
    meltingPoint: 1663,
    boilingPoint: 3402,
    oxidationState: [3],
    electronegativity: 1.27,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/lutetium.html",
  },
  hf: {
    atomicNumber: 72,
    symbol: "Hf",
    fullName: "Hafnium",
    electronicConfiguration: "[Xe] 4f14 5d2 6s2",
    position: "G4 P6",
    atomicWeight: 178.49,
    atomicRadius: 159,
    density: 13.31,
    state: "Solid",
    meltingPoint: 2233,
    boilingPoint: 4603,
    oxidationState: [4],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/hafnium.html",
  },
  ta: {
    atomicNumber: 73,
    symbol: "Ta",
    fullName: "Tantalum",
    electronicConfiguration: "[Xe] 4f14 5d3 6s2",
    position: "G5 P6",
    atomicWeight: 180.95,
    atomicRadius: 146,
    density: 16.69,
    state: "Solid",
    meltingPoint: 3017,
    boilingPoint: 5458,
    oxidationState: [5],
    electronegativity: 1.5,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/tantalum.html",
  },
  w: {
    atomicNumber: 74,
    symbol: "W",
    fullName: "Tungsten",
    electronicConfiguration: "[Xe] 4f14 5d4 6s2",
    position: "G6 P6",
    atomicWeight: 183.84,
    atomicRadius: 139,
    density: 19.25,
    state: "Solid",
    meltingPoint: 3422,
    boilingPoint: 5555,
    oxidationState: [6],
    electronegativity: 2.36,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/tungsten.html",
  },
  re: {
    atomicNumber: 75,
    symbol: "Re",
    fullName: "Rhenium",
    electronicConfiguration: "[Xe] 4f14 5d5 6s2",
    position: "G7 P6",
    atomicWeight: 186.21,
    atomicRadius: 137,
    density: 21.02,
    state: "Solid",
    meltingPoint: 3186,
    boilingPoint: 5596,
    oxidationState: [7],
    electronegativity: 1.9,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/rhenium.html",
  },
  os: {
    atomicNumber: 76,
    symbol: "Os",
    fullName: "Osmium",
    electronicConfiguration: "[Xe] 4f14 5d6 6s2",
    position: "G8 P6",
    atomicWeight: 190.23,
    atomicRadius: 135,
    density: 22.59,
    state: "Solid",
    meltingPoint: 3033,
    boilingPoint: 5012,
    oxidationState: [4],
    electronegativity: 2.2,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/osmium.html",
  },
  ir: {
    atomicNumber: 77,
    symbol: "Ir",
    fullName: "Iridium",
    electronicConfiguration: "[Xe] 4f14 5d7 6s2",
    position: "G9 P6",
    atomicWeight: 192.22,
    atomicRadius: 137,
    density: 22.56,
    state: "Solid",
    meltingPoint: 2466,
    boilingPoint: 4428,
    oxidationState: [4],
    electronegativity: 2.2,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/iridium.html",
  },
  pt: {
    atomicNumber: 78,
    symbol: "Pt",
    fullName: "Platinum",
    electronicConfiguration: "[Xe] 4f14 5d9 6s1",
    position: "G10 P6",
    atomicWeight: 195.08,
    atomicRadius: 139,
    density: 21.45,
    state: "Solid",
    meltingPoint: 1768.3,
    boilingPoint: 3825,
    oxidationState: [2, 4],
    electronegativity: 2.28,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/platinum.html",
  },
  au: {
    atomicNumber: 79,
    symbol: "Au",
    fullName: "Gold",
    electronicConfiguration: "[Xe] 4f14 5d10 6s1",
    position: "G11 P6",
    atomicWeight: 196.97,
    atomicRadius: 144,
    density: 19.32,
    state: "Solid",
    meltingPoint: 1064,
    boilingPoint: 2970,
    oxidationState: [1, 3],
    electronegativity: 2.54,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/gold.html",
  },
  hg: {
    atomicNumber: 80,
    symbol: "Hg",
    fullName: "Mercury",
    electronicConfiguration: "[Xe] 4f14 5d10 6s2",
    position: "G12 P6",
    atomicWeight: 200.59,
    atomicRadius: 150,
    density: 13.53,
    state: "Liquid",
    meltingPoint: -38.83,
    boilingPoint: 356.7,
    oxidationState: [1, 2],
    electronegativity: 2.0,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/mercury.html",
  },
  tl: {
    atomicNumber: 81,
    symbol: "Tl",
    fullName: "Thallium",
    electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p1",
    position: "G13 P6",
    atomicWeight: 204.38,
    atomicRadius: 170,
    density: 11.85,
    state: "Solid",
    meltingPoint: 304,
    boilingPoint: 1473,
    oxidationState: [1, 3],
    electronegativity: 2.04,
    electronGainEnthalpy: 0,
    electronAffinity: 0.2,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Reactive",
    url: "element/thallium.html",
  },
  pb: {
    atomicNumber: 82,
    symbol: "Pb",
    fullName: "Lead",
    electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p2",
    position: "G14 P6",
    atomicWeight: 207.2,
    atomicRadius: 175,
    density: 11.34,
    state: "Solid",
    meltingPoint: 327.5,
    boilingPoint: 1749,
    oxidationState: [2, 4],
    electronegativity: 2.33,
    electronGainEnthalpy: 0,
    electronAffinity: 0.36,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/lead.html",
  },
  bi: {
    atomicNumber: 83,
    symbol: "Bi",
    fullName: "Bismuth",
    electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p3",
    position: "G15 P6",
    atomicWeight: 208.98,
    atomicRadius: 155,
    density: 9.78,
    state: "Solid",
    meltingPoint: 271.4,
    boilingPoint: 1564,
    oxidationState: [3, 5],
    electronegativity: 2.02,
    electronGainEnthalpy: 0,
    electronAffinity: 0.94,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Stable",
    url: "element/bismuth.html",
  },
  po: {
    atomicNumber: 84,
    symbol: "Po",
    fullName: "Polonium",
    electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p4",
    position: "G16 P6",
    atomicWeight: 209,
    atomicRadius: 168,
    density: 9.32,
    state: "Solid",
    meltingPoint: 254,
    boilingPoint: 962,
    oxidationState: [2, 4, 6],
    electronegativity: 2.0,
    electronGainEnthalpy: 0,
    electronAffinity: 1.9,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/polonium.html",
  },
  at: {
    atomicNumber: 85,
    symbol: "At",
    fullName: "Astatine",
    electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p5",
    position: "G17 P6",
    atomicWeight: 210,
    atomicRadius: 150,
    density: 7,
    state: "Solid",
    meltingPoint: 302,
    boilingPoint: 337,
    oxidationState: [1, 3, 5, 7],
    electronegativity: 2.2,
    electronGainEnthalpy: 0,
    electronAffinity: 2.8,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/astatine.html",
  },
  rn: {
    atomicNumber: 86,
    symbol: "Rn",
    fullName: "Radon",
    electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p6",
    position: "G18 P6",
    atomicWeight: 222,
    atomicRadius: 120,
    density: 9.73,
    state: "Gas",
    meltingPoint: -71,
    boilingPoint: -61.7,
    oxidationState: [2, 4, 6],
    electronegativity: 2.2,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/radon.html",
  },
  fr: {
    atomicNumber: 87,
    symbol: "Fr",
    fullName: "Francium",
    electronicConfiguration: "[Rn] 7s1",
    position: "G1 P7",
    atomicWeight: 223,
    atomicRadius: 260,
    density: 1.87,
    state: "Solid",
    meltingPoint: 27,
    boilingPoint: 677,
    oxidationState: [1],
    electronegativity: 0.7,
    electronGainEnthalpy: 0,
    electronAffinity: 0.47,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/francium.html",
  },
  ra: {
    atomicNumber: 88,
    symbol: "Ra",
    fullName: "Radium",
    electronicConfiguration: "[Rn] 7s2",
    position: "G2 P7",
    atomicWeight: 226,
    atomicRadius: 215,
    density: 5.5,
    state: "Solid",
    meltingPoint: 700,
    boilingPoint: 1737,
    oxidationState: [2],
    electronegativity: 0.9,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/radium.html",
  },
  ac: {
    atomicNumber: 89,
    symbol: "Ac",
    fullName: "Actinium",
    electronicConfiguration: "[Rn] 6d1 7s2",
    position: "G3 P7",
    atomicWeight: 227,
    atomicRadius: 195,
    density: 10.07,
    state: "Solid",
    meltingPoint: 1050,
    boilingPoint: 3200,
    oxidationState: [3],
    electronegativity: 1.1,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/actinium.html",
  },
  th: {
    atomicNumber: 90,
    symbol: "Th",
    fullName: "Thorium",
    electronicConfiguration: "[Rn] 6d2 7s2",
    position: "G3 P7",
    atomicWeight: 232.04,
    atomicRadius: 180,
    density: 11.72,
    state: "Solid",
    meltingPoint: 1750,
    boilingPoint: 4788,
    oxidationState: [4],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/thorium.html",
  },
  pa: {
    atomicNumber: 91,
    symbol: "Pa",
    fullName: "Protactinium",
    electronicConfiguration: "[Rn] 5f2 6d1 7s2",
    position: "G3 P7",
    atomicWeight: 231.04,
    atomicRadius: 163,
    density: 15.37,
    state: "Solid",
    meltingPoint: 1568,
    boilingPoint: 4027,
    oxidationState: [5],
    electronegativity: 1.5,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/protactinium.html",
  },
  u: {
    atomicNumber: 92,
    symbol: "U",
    fullName: "Uranium",
    electronicConfiguration: "[Rn] 5f3 6d1 7s2",
    position: "G3 P7",
    atomicWeight: 238.03,
    atomicRadius: 156,
    density: 19.05,
    state: "Solid",
    meltingPoint: 1132,
    boilingPoint: 4131,
    oxidationState: [3, 4, 5, 6],
    electronegativity: 1.38,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/uranium.html",
  },
  np: {
    atomicNumber: 93,
    symbol: "Np",
    fullName: "Neptunium",
    electronicConfiguration: "[Rn] 5f4 6d1 7s2",
    position: "G3 P7",
    atomicWeight: 237,
    atomicRadius: 155,
    density: 20.45,
    state: "Solid",
    meltingPoint: 644,
    boilingPoint: 4174,
    oxidationState: [3, 4, 5, 6, 7],
    electronegativity: 1.36,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/neptunium.html",
  },
  pu: {
    atomicNumber: 94,
    symbol: "Pu",
    fullName: "Plutonium",
    electronicConfiguration: "[Rn] 5f6 7s2",
    position: "G3 P7",
    atomicWeight: 244,
    atomicRadius: 151,
    density: 19.84,
    state: "Solid",
    meltingPoint: 639.5,
    boilingPoint: 3228,
    oxidationState: [3, 4, 5, 6, 7],
    electronegativity: 1.28,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/plutonium.html",
  },
  am: {
    atomicNumber: 95,
    symbol: "Am",
    fullName: "Americium",
    electronicConfiguration: "[Rn] 5f7 7s2",
    position: "G3 P7",
    atomicWeight: 243,
    atomicRadius: 175,
    density: 13.67,
    state: "Solid",
    meltingPoint: 1176,
    boilingPoint: 2011,
    oxidationState: [3, 4, 5, 6],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/americium.html",
  },
  cm: {
    atomicNumber: 96,
    symbol: "Cm",
    fullName: "Curium",
    electronicConfiguration: "[Rn] 5f7 6d1 7s2",
    position: "G3 P7",
    atomicWeight: 247,
    atomicRadius: 170,
    density: 13.51,
    state: "Solid",
    meltingPoint: 1340,
    boilingPoint: 3110,
    oxidationState: [3, 4],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/curium.html",
  },
  bk: {
    atomicNumber: 97,
    symbol: "Bk",
    fullName: "Berkelium",
    electronicConfiguration: "[Rn] 5f9 7s2",
    position: "G3 P7",
    atomicWeight: 247,
    atomicRadius: 170,
    density: 14.78,
    state: "Solid",
    meltingPoint: 986,
    boilingPoint: 2627,
    oxidationState: [3, 4],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/berkelium.html",
  },
  cf: {
    atomicNumber: 98,
    symbol: "Cf",
    fullName: "Californium",
    electronicConfiguration: "[Rn] 5f10 7s2",
    position: "G3 P7",
    atomicWeight: 251,
    atomicRadius: 170,
    density: 15.1,
    state: "Solid",
    meltingPoint: 900,
    boilingPoint: 1740,
    oxidationState: [3, 4],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/californium.html",
  },
  es: {
    atomicNumber: 99,
    symbol: "Es",
    fullName: "Einsteinium",
    electronicConfiguration: "[Rn] 5f11 7s2",
    position: "G3 P7",
    atomicWeight: 252,
    atomicRadius: 170,
    density: 8.84,
    state: "Solid",
    meltingPoint: 860,
    boilingPoint: 996,
    oxidationState: [3],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/einsteinium.html",
  },
  fm: {
    atomicNumber: 100,
    symbol: "Fm",
    fullName: "Fermium",
    electronicConfiguration: "[Rn] 5f12 7s2",
    position: "G3 P7",
    atomicWeight: 257,
    atomicRadius: 170,
    density: 9.7,
    state: "Solid",
    meltingPoint: 1527,
    boilingPoint: "Unknown",
    oxidationState: [3],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/fermium.html",
  },
  md: {
    atomicNumber: 101,
    symbol: "Md",
    fullName: "Mendelevium",
    electronicConfiguration: "[Rn] 5f13 7s2",
    position: "G3 P7",
    atomicWeight: 258,
    atomicRadius: 173,
    density: 10.3,
    state: "Solid",
    meltingPoint: 827,
    boilingPoint: "Unknown",
    oxidationState: [2, 3],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/mendelevium.html",
  },
  no: {
    atomicNumber: 102,
    symbol: "No",
    fullName: "Nobelium",
    electronicConfiguration: "[Rn] 5f14 7s2",
    position: "G3 P7",
    atomicWeight: 259,
    atomicRadius: 175,
    density: 9.9,
    state: "Solid",
    meltingPoint: 827,
    boilingPoint: "Unknown",
    oxidationState: [2, 3],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/nobelium.html",
  },
  lr: {
    atomicNumber: 103,
    symbol: "Lr",
    fullName: "Lawrencium",
    electronicConfiguration: "[Rn] 5f14 7s2 7p1",
    position: "G3 P7",
    atomicWeight: 262,
    atomicRadius: 171,
    density: 15.6,
    state: "Solid",
    meltingPoint: 1627,
    boilingPoint: "Unknown",
    oxidationState: [3],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/lawrencium.html",
  },
  rf: {
    atomicNumber: 104,
    symbol: "Rf",
    fullName: "Rutherfordium",
    electronicConfiguration: "[Rn] 5f14 6d2 7s2",
    position: "G4 P7",
    atomicWeight: 267,
    atomicRadius: 157,
    density: 23.2,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [4],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/rutherfordium.html",
  },
  db: {
    atomicNumber: 105,
    symbol: "Db",
    fullName: "Dubnium",
    electronicConfiguration: "[Rn] 5f14 6d3 7s2",
    position: "G5 P7",
    atomicWeight: 270,
    atomicRadius: 149,
    density: 29.3,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [5],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/dubnium.html",
  },
  sg: {
    atomicNumber: 106,
    symbol: "Sg",
    fullName: "Seaborgium",
    electronicConfiguration: "[Rn] 5f14 6d4 7s2",
    position: "G6 P7",
    atomicWeight: 271,
    atomicRadius: 143,
    density: 35.0,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [6],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/seaborgium.html",
  },
  bh: {
    atomicNumber: 107,
    symbol: "Bh",
    fullName: "Bohrium",
    electronicConfiguration: "[Rn] 5f14 6d5 7s2",
    position: "G7 P7",
    atomicWeight: 270,
    atomicRadius: 141,
    density: 37.1,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [7],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/bohrium.html",
  },
  hs: {
    atomicNumber: 108,
    symbol: "Hs",
    fullName: "Hassium",
    electronicConfiguration: "[Rn] 5f14 6d6 7s2",
    position: "G8 P7",
    atomicWeight: 277,
    atomicRadius: 134,
    density: 40.7,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [8],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/hassium.html",
  },
  mt: {
    atomicNumber: 109,
    symbol: "Mt",
    fullName: "Meitnerium",
    electronicConfiguration: "[Rn] 5f14 6d7 7s2",
    position: "G9 P7",
    atomicWeight: 278,
    atomicRadius: 129,
    density: 37.4,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [9],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/meitnerium.html",
  },
  ds: {
    atomicNumber: 110,
    symbol: "Ds",
    fullName: "Darmstadtium",
    electronicConfiguration: "[Rn] 5f14 6d8 7s2",
    position: "G10 P7",
    atomicWeight: 281,
    atomicRadius: 128,
    density: 34.8,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [8],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/darmstadtium.html",
  },
  rg: {
    atomicNumber: 111,
    symbol: "Rg",
    fullName: "Roentgenium",
    electronicConfiguration: "[Rn] 5f14 6d9 7s2",
    position: "G11 P7",
    atomicWeight: 282,
    atomicRadius: 121,
    density: 28.7,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [3],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/roentgenium.html",
  },
  cn: {
    atomicNumber: 112,
    symbol: "Cn",
    fullName: "Copernicium",
    electronicConfiguration: "[Rn] 5f14 6d10 7s2",
    position: "G12 P7",
    atomicWeight: 285,
    atomicRadius: 122,
    density: 23.7,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [2],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/copernicium.html",
  },
  nh: {
    atomicNumber: 113,
    symbol: "Nh",
    fullName: "Nihonium",
    electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p1",
    position: "G13 P7",
    atomicWeight: 286,
    atomicRadius: 136,
    density: 16,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [1, 3],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/nihonium.html",
  },
  fl: {
    atomicNumber: 114,
    symbol: "Fl",
    fullName: "Flerovium",
    electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p2",
    position: "G14 P7",
    atomicWeight: 289,
    atomicRadius: 143,
    density: 14,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [2, 4],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/flerovium.html",
  },
  mc: {
    atomicNumber: 115,
    symbol: "Mc",
    fullName: "Moscovium",
    electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p3",
    position: "G15 P7",
    atomicWeight: 290,
    atomicRadius: 135,
    density: 13.5,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [1, 3],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/moscovium.html",
  },
  lv: {
    atomicNumber: 116,
    symbol: "Lv",
    fullName: "Livermorium",
    electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p4",
    position: "G16 P7",
    atomicWeight: 293,
    atomicRadius: 139,
    density: 12.9,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [2, 4],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/livermorium.html",
  },
  ts: {
    atomicNumber: 117,
    symbol: "Ts",
    fullName: "Tennessine",
    electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p5",
    position: "G17 P7",
    atomicWeight: 294,
    atomicRadius: 138,
    density: 7.2,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [1, 3, 5],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/tennessine.html",
  },
  og: {
    atomicNumber: 118,
    symbol: "Og",
    fullName: "Oganesson",
    electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p6",
    position: "G18 P7",
    atomicWeight: 294,
    atomicRadius: 152,
    density: 4.9,
    state: "Solid",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    oxidationState: [0],
    electronegativity: 1.3,
    electronGainEnthalpy: 0,
    electronAffinity: 0,
    protonAffinity: 0,
    autoIgnitionTemperature: "Non-flammable",
    airSensitivity: "Radioactive",
    url: "element/oganesson.html",
  },
};

console.log("props done");
